//! `saleae`: drive Saleae logic analyzers through the headless Logic 2 automation server (gRPC).
//!
//! The command tree and handlers live in `cli.rs`; this file only wires the modules, so that a build without the
//! Saleae proto (docs.rs has no network: `cfg(saleae_stub_proto)`, see `build.rs`) still compiles.

#[cfg(not(saleae_stub_proto))]
mod analyzers;
#[cfg(not(saleae_stub_proto))]
mod capture;
#[cfg(not(saleae_stub_proto))]
mod cli;
#[cfg(not(saleae_stub_proto))]
mod complete;
#[cfg(not(saleae_stub_proto))]
mod parse;
#[cfg(not(saleae_stub_proto))]
mod server;
#[cfg(not(saleae_stub_proto))]
mod summary;

/// The gRPC API, generated by `build.rs` from Saleae's `saleae.proto`.
#[cfg(not(saleae_stub_proto))]
pub mod pb {
    tonic::include_proto!("saleae.automation");
}

#[cfg(not(saleae_stub_proto))]
fn main() {
    cli::main()
}

#[cfg(saleae_stub_proto)]
fn main() {
    eprintln!("saleae: built without the Saleae automation API (stub build, see build.rs)");
    std::process::exit(2);
}
