//! Typed Rust API for Saleae logic analyzers (Logic 8, Logic Pro 8/16) over the headless Logic 2 automation
//! server (gRPC): [`server`] installs/finds/starts/stops it and connects, [`capture`] runs captures,
//! [`analyzer`] adds protocol analyzers, [`export`] writes raw and analyzer data, [`summary`] turns an
//! analyzer's data table into a short human/JSON summary, and [`decode`] combines capture + analyzer + summary
//! into the one-shot flow most callers want.
//!
//! See the workspace README and `AGENTS.md` for how the gRPC API (`saleae.proto`) is fetched at build time, and
//! for the `SALEAE_PROTO_DIR` / `DOCS_RS` build-time overrides (the latter builds this crate with
//! `cfg(saleae_stub_proto)`: no modules, since none of them can exist without the generated `pb` types).

#[cfg(not(saleae_stub_proto))]
pub mod analyzer;
#[cfg(not(saleae_stub_proto))]
pub mod capture;
#[cfg(not(saleae_stub_proto))]
pub mod decode;
#[cfg(not(saleae_stub_proto))]
pub mod device;
#[cfg(not(saleae_stub_proto))]
mod error;
#[cfg(not(saleae_stub_proto))]
pub mod export;
#[cfg(not(saleae_stub_proto))]
pub mod fmt;
#[cfg(not(saleae_stub_proto))]
pub mod server;
#[cfg(not(saleae_stub_proto))]
pub mod summary;

#[cfg(not(saleae_stub_proto))]
pub use error::{Error, Result};

/// The gRPC API, generated by `build.rs` from Saleae's `saleae.proto`.
#[cfg(not(saleae_stub_proto))]
pub mod pb {
    tonic::include_proto!("saleae.automation");
}
